### ISSUE TITLE
TypeError: Cannot read property 'ucrop' of undefined - NativeScript App

### ISSUE THREAD

**Issue by Nixon1979** [bthurlow/nativescript-imagecropper#1]
Added the plugin to my project, carried out the modification in Androidmanifest.xml and defined in my js - var imageCropper = require("nativescript-imagecropper");
.. trying to build the app gives out the following error.. Need help here.

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.MissingPerson/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'ucrop' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/nativescript-imagecropper/imagecropper.js', line: 8, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/shared/utils/utils.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/views/login/login.js', line: 5, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/globals/globals.js', line: 19, column: 16
	Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame-common.js', line: 72, column: 40
	Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame-common.js', line: 148, column: 20
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame.js', line: 616, column: 19

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
	at android.app.ActivityThread.access$900(ActivityThread.java:181)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6145)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'ucrop' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/nativescript-imagecropper/imagecropper.js', line: 8, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/shared/utils/utils.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.MissingPerson/files/app/views/login/login.js', line: 5, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/globals/globals.js', line: 19, column: 16
	Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame-common.js', line: 72, column: 40
	Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame-common.js', line: 148, column: 20
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.MissingPerson/files/app/tns_modules/ui/frame/frame.js', line: 616, column: 19

	at com.tns.Platform.callJSMethodNative(Native Method)
	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
	at com.tns.Platform.callJSMethod(Platform.java:715)
	at com.tns.Platform.callJSMethod(Platform.java:694)
	at com.tns.Platform.callJSMethod(Platform.java:684)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:14)
	at android.app.Activity.performCreate(Activity.java:6374)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2752)
	... 10 more

**Comment by Nixon1979** [comment]
add to this got the below error too 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MissingPerson'.
> No flavor is associated with flavor dimension 'nativescriptimagecropper'.

**Comment by bthurlow** [comment]
Try v0.0.5 and see if that resolves your problem.  If not, reopen this issue.

**Comment by Nixon1979** [comment]
Nope still getting the same error after the update to 0.0.5

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MissingPerson'.
> No flavor is associated with flavor dimension 'nativescriptimagecropper'.


I cant re-open this issue as you have closed it with rights as repo collaborator.. let me know if you need me to add another issue for the same... Other way could be if you can re-open the issue.

Thanks for taking this up :)

**Comment by bthurlow** [comment]
That particular error appears to be related to your applications build.gradle specifically the flavorDimensions and the productFlavors settings.

I wasn't able to reproduce that specific error when I was patching the plugin, but I was getting your first error.

Have you tried to run the demo app included with the plugin?

**Comment by bthurlow** [comment]
I think I found the issue.  Going to apply a patch and bump the version.

**Comment by Nixon1979** [comment]
great will wait for it and then jump on to bed...

**Comment by bthurlow** [comment]
Just pushed 0.0.6 to npm.  Let me know if that works for you.

**Comment by Nixon1979** [comment]
Great will check right away

**Comment by Nixon1979** [comment]
Sorry got a new error 
-----------------------------

Download https://jcenter.bintray.com/com/yalantis/ucrop/1.3.2/ucrop-1.3.2.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'MissingPerson'.
> Could not resolve all dependencies for configuration ':_nicNativescript-local-notificationsNativescript-plugin-google-play-servicesDebugCompile'.
   > Could not find com.android.support:appcompat-v7:23.2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/missingPerson/mobileApp/platforms/android/libs/aar/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/missingPerson/mobileApp/platforms/android/libs/aar/appcompat-v7.jar
         file:/Users/nixon/projects/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         file:/Users/nixon/projects/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         file:/Users/nixon/projects/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
     Required by:
         :MissingPerson:unspecified
   > Could not find com.android.support:appcompat-v7:23.2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/missingPerson/mobileApp/platforms/android/libs/aar/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/missingPerson/mobileApp/platforms/android/libs/aar/appcompat-v7.jar
         file:/Users/nixon/projects/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         file:/Users/nixon/projects/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
         file:/Users/nixon/projects/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.pom
         file:/Users/nixon/projects/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.2.0/appcompat-v7-23.2.0.jar
     Required by:
         :MissingPerson:unspecified > com.yalantis:ucrop:1.3.2

**Comment by bthurlow** [comment]
Sounds like you need to run the Android SDK manager, scroll down to extras, and choose the Android Support Repository and either install or update it.

**Comment by Nixon1979** [comment]
For some reason even after the update its giving the same error. Also found that the support library updated it only to 23.1.1 while here the build is requiring 23.2.0

Will check whats missing

**Comment by Nixon1979** [comment]
The last one was my issue.. this issue if closed now... will start on the implementation..

Thanks a ton!!!

**Comment by Nixon1979** [comment]
I wish there was a place for not just raising issues but also sending out awesome thanks to the creators here on GitHub 👍  It works as a charm now and solved one of my most critical parts of the app. Thanks a lot Brian!!!
