### ISSUE TITLE
nativescript-imagecropper in NativeScript 3.0

### ISSUE THREAD

**Issue by SandipFichadiya** [bthurlow/nativescript-imagecropper#14]
Hi,
nativescript-imagecropper Plugin is not working in Nativescript 3.0.3 Version.
It gives me undefined error in catch clause.
Is there another way to implement nativescript-imagecropper Plugin for Nativescript 3.0.3 Version?

**Comment by shiv19** [comment]
Support has been added now :)
download plugin version 0.1.0
