### ISSUE TITLE
Build issue for android - transformClassesWithDexForF0F1F2F3F4F5F6F7F8F9Debug

### ISSUE THREAD

**Issue by shabib3** [bthurlow/nativescript-imagecropper#16]
Hey after install the plugin and write code to use its functionality I tried to build my project and this is build error:
```

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformClassesWithDexForF0F1F2F3F4F5F6F7F8F9Debug'.
> 
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

### Which platform(s) does your issue occur on?
- Android (Didn't check on IOS)
- API 25
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): tns-android - 3.4.0-2017-10-31-1 (tns platfrom add android@next)
- Plugin(s): 

```
"dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/platform-browser-dynamic": "~4.2.0",
    "@angular/router": "~4.2.0",
    "email-validator": "^1.1.1",
    "font-awesome": "^4.7.0",
    "nativescript-angular": "~4.2.0",
    "nativescript-background-http": "^3.0.0",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-calendar": "^1.2.2",
    "nativescript-camera": "^3.0.1",
    "nativescript-floatingactionbutton": "^3.0.1",
    "nativescript-imagecropper": "^0.1.2",
    "nativescript-imagepicker": "^3.0.4",
    "nativescript-plugin-firebase": "^4.0.5",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-web-image-cache": "^4.2.2",
    "password-validator": "^4.0.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.3.0",
    "typescript-collections": "^1.2.3",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
```

**Comment by shiv19** [comment]
Hi @shabib3 
Please enable multidex support in your app.
To do this,
Open app.gradle file in App_Resources/android folder 

Inside the defaultConfig area, set `multiDexEnabled true`
```
android {  
  defaultConfig {  
    multiDexEnabled true
  }
}
```
Like this ☝️

**Comment by ogmedia** [comment]
I seem to be having a similar issue, it seems related. Removing the plugin resolves the issue, but it works without any problems in iOS.
`* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.android.support:multidex:26.0.0-alpha1.
  Searched in the following locations:`

I added multiDexEnabled to my app.gradle file, but still getting the error.

`  "dependencies": {
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-carousel": "^3.1.1",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-feedback": "^1.1.2",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-https": "^1.0.1",
    "nativescript-imagepicker": "^6.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-secure-storage": "^2.2.2",
    "nativescript-theme-core": "~1.0.4",
    "tns-core-modules": "^4.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "raw-loader": "~0.5.1",
    "css-loader": "~0.28.7",
    "nativescript-worker-loader": "~0.8.1",
    "resolve-url-loader": "~2.2.1",
    "extract-text-webpack-plugin": "~3.0.2",
    "uglifyjs-webpack-plugin": "~1.1.6"
  }`

This occurs on android 4.0.1

**Comment by shabib3** [comment]
@shiv19 @bthurlow - 
@ogmedia is right...There is any idea for solution here?

**Comment by shiv19** [comment]
@DickSmith
do you know what is going wrong here?

**Comment by shabib3** [comment]
@DickSmith - 
I think it relates to `nativescript-imagepicker` version 6.0.1

**Comment by DickSmith** [comment]
@shiv19 Yeah, they made a change on `tns-android@4.0.1` I'll send a PR.
