### ISSUE TITLE
naticescript-imagecropper not working

### ISSUE THREAD

**Issue by SugumarParthi** [bthurlow/nativescript-imagecropper#17]
# **This is my code:**
camera.takePicture({width:300,height:300,keepAspectRatio:true})
.then((imageAsset) => {
let source = new imageSource.ImageSource();
source.fromAsset(imageAsset).then((imageSource1) => {
var imageCropper = new icModule.ImageCropper();
imageCropper.show(imageSource1).then((args) => {
console.dir(args);
if(args.image !== null){
imageView.src = args.image;
}
})
.catch(function(e){
console.dir(e);
});
});
}).catch((err) => {
console.log("Error -> " + err.message);
});

# **am getting this error:**
TypeError: undefined is not an object (evaluating ‘_options.lockSquare’)

**# platform**
-Nativescript(iOS)

**# versions**
- Nativescript -> 3.3.0
- tns-ios   -> 3.3.0

**# plugins**
tns plugin add nativescript-imagecropper
tns plugin add nativescript-camera

**Comment by shiv19** [comment]
@SugumarParthi 
Please change this part
`imageCropper.show(imageSource1)`
to this
`imageCropper.show(imageSource1,{lockSquare: false})`
