### ISSUE TITLE
can't run demo

### ISSUE THREAD

**Issue by vasyliv** [bthurlow/nativescript-imagecropper#20]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android versions 
- device. What type of device **xiaomi redmi note 4x**?

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it): **3.4.0**
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1.) git clone https://github.com/bthurlow/nativescript-imagecropper.git
2.) cd nativescript-imagecropper
3.) cd demo
4.) tns run android
 error:
``
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScri
ptException: Failed to find module: "nativescript-imagecropper", relative to: app/tns_modules/
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:163)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6237)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
``
### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by shiv19** [comment]
@vasyliv
That is not how you run the demo. 

Clone the repo
Open src folder

Run, 
`npm run demo.android`
