### ISSUE TITLE
Native libraries are outdated

### ISSUE THREAD

**Issue by odnamrataizem** [bthurlow/nativescript-imagecropper#22]
The native libraries this plugin uses, both Android and iOS, are quite outdated: uCrop is at 2.2.1 (the plugin is using 1.5.0), and TOCropViewController is at 2.3.6 (the plugin is using 1.3.3).

I've run into some issues on both Android and iOS, and because they are specifically *UI* issues, I'm 100% sure they come from the native libraries rather than the plugin itself. Upgrading them, therefore, might not only solve these issues (and a lot more), but also bring in new features like #18 and (in the case of iOS) iPhone X support.

**Comment by shiv19** [comment]
@odnamrataizem Please use the latest version 1.0.1
