### ISSUE TITLE
Setting Options In Nativescript

### ISSUE THREAD

**Issue by dsum27** [bthurlow/nativescript-imagecropper#3]
Hello, this is a great package. Could you tell me if I can use more options besides the ones listed below in a nativescript set up?

Option | Type   | Description
------ | ------ | ------------------------------------------------
width  | number | The width of the image you would like returned.
height | number | The height of the image you would like returned.

Specifically 

- change actionbar color, 
- specify save location,
- change screen background color,
- return cropbox x, y, width, and height, image x, y, width, and height
- change cropbox aspect ratio
- allow only 90 degree rotations (I can rotate image after crop)
- change color to black and white(I can change image color after crop)

             cropper.show(picture,{width:300,height:300, moreoptions}).then(function(args){
                 console.log("cropper.cropBoxX" + cropper.cropBoxX);
                 console.log("cropper.cropBoxY" + cropper.cropBoxY);
                 console.log("cropper.cropBoxWidth" + cropper.cropBoxWidth);
                 console.log("cropper.cropBoxHeight" + cropper.cropBoxHeight);
                 console.log(JSON.stringify(args));
             })
             .catch(function(e){
                 console.log(e);
             });

**Comment by bthurlow** [comment]
- change actionbar color
 - Not available in current version
- specify save location
 - Saving is up to you to save the returned imagesource object.
- change screen background color
 - Not Available in current version
- return cropbox x, y, width, and height, image x, y, width, and height
 - Not available in current version
- change cropbox aspect ratio
 - There is not a setting for this, however, aspect ratio is changeable inside of the cropper
- allow only 90 degree rotations (I can rotate image after crop)
 - No setting to control rotation, however, rotation is available inside the cropper
- change color to black and white(I can change image color after crop)
 - Filters are not available.  This plugin is designed purely as a cropper.

**Comment by dsum27** [comment]
@bthurlow thank you!
