### ISSUE TITLE
Problem with multidex in release build(Android)

### ISSUE THREAD

**Issue by Ablankzin** [bthurlow/nativescript-imagecropper#30]
Hello, I'm having a problem while doing the build release of my application. The problem is in choosing the multidex version. It is looking for the SDK version. So when it goes through the multidex it looks for version 26 (For example), and the version that exists is 1.0.0.

### Which platform(s) does your issue occur on?
- Android(Release signed with --release)
Command: tns build android --bundle --env.aot --release --copy-to xxxx.apk --release --keyStorePath /path.keystore --keyStorePassword xxx --keyStoreAlias xxx --keyStoreAliasPassword xxx --env.snapshot

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.1
- Cross-platform modules: "version": "4.0.0",
- Runtime(s): 4.0.1
- Plugin(s): `
"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-imagecropper": "^1.0.1",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "~4.0.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
`

### Please, tell us how to recreate the issue in as much detail as possible. 
Only execute the any project with this plugin with this command:

tns build android --bundle --env.aot --release --copy-to xxxx.apk --release --keyStorePath /path.keystore --keyStorePassword xxx --keyStoreAlias xxx --keyStoreAliasPassword xxx --env.snapshot

**Comment by shiv19** [comment]
Please update to v1.0.4
Issue resolved

**Comment by shabib3** [comment]
@DickSmith @shiv19 - KINGS! Thanks a lot!!
