### ISSUE TITLE
 Failed to build plugin nativescript-imagecropper

### ISSUE THREAD

**Issue by momoling** [bthurlow/nativescript-imagecropper#33]
Unable to apply changes on device: 79BMADR7QZD25. Error is: Failed to build plugin nativescript-imagecropper :
Error: Command gradlew.bat failed with exit code 1 Error output:
C:\Users\Administrator.gradle\caches\transforms-1\files-1.1\ucrop-2.2.2-native.aar\bfa85db65d82ba41411e23f89fa6657f\res\values\values.xml:72:5-77:13: AAPT: resource attr/selectableItemBackground (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackground) not found.

D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:75: AAPT: resource attr/selectableItemBackgroundBorderless (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackgroundBorderless) not found.

D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:69: error: resource attr/selectableItemBackground (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackground) not found.
D:\HelloWorld\platforms\tempPlugin\nativescript_imagecropper\build\intermediates\res\merged\release\values\values.xml:75: error: resource attr/selectableItemBackgroundBorderless (aka org.nativescript.nativescript_imagecropper:attr/selectableItemBackgroundBorderless) not found.
error: failed linking references.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':verifyReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by EvenHus** [comment]
Any update's on this one?

**Comment by JPM84** [comment]
This is a blocker for updating our project to {N}4 on android devices.

**Comment by shiv19** [comment]
I am still using `"nativescript-imagecropper": "^0.1.2"` <- this version.
working fine with {N} 4.0

**Comment by simano65** [comment]
Version: "^0.1.2" cause problem with iOs

**Comment by AradhanaR** [comment]
I am facing the same issue, with latest version build is getting failed with following error :

> Error is: Failed to build plugin nativescript-imagecropper :
Error: Command gradlew.bat failed with exit code 1 Error output:

And with nativescript-imagecropper": "^0.1.2  not working for iOS.

**Comment by xnramx** [comment]
I have the same issue. In iOS the crop does not work with the version 0.1.2. And the new one does not compile in Android. Is there any solution?

**Comment by shiv19** [comment]
Issue resolved.
Please update to v1.0.3

**Comment by Tompote** [comment]
Hi ! I tried v1.0.4 with NS 4.1 (deleted node_modules/hook/platforms) and it doesn't seem to pass gradle build.
I get this error:

Gradle build...
         + setting applicationId
         + applying user-defined configuration from /home/thomas/KazakorseFrontend/nativescript/app/App_Resources/Android/app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-feedback/platforms/android/nativescript_feedback.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-imagecropper/platforms/android/nativescript_imagecropper.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-imagepicker/platforms/android/nativescript_imagepicker.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-plugin-firebase/platforms/android/firebase-release.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-purchase/platforms/android/inappbillinghelper-release.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-sentry/platforms/android/nativescript_sentry.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-ui-listview/platforms/android/TNSListView-release.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
         + adding aar plugin dependency: /home/thomas/KazakorseFrontend/nativescript/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file. Try supplying a main-dex list.
# methods: 66454 > 65536

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
//bunch of jar

  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by shiv19** [comment]
@Tompote 
Looks like you haven't enabled multidex
open app/App_Resources/Android/app.gradle

in there,
inside 
```
android {
    defaultConfig {
    
    }
}
```
add `multiDexEnabled true`

**Comment by Tompote** [comment]
Well that was a fast answer :). Works great ! Thanks a lot !

**Comment by momoling** [comment]
@shiv19 thank you

**Comment by phacic** [comment]
The issue is still present in tns 4.2 and nativescript-imagecropper 1.0.4

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':verifyReleaseResources'

**Comment by shiv19** [comment]
I've been unable to reproduce this issue. @phacic
Can you provide a demo project to reproduce this issue?

**Comment by borjasanchez-bitcode** [comment]
I have the same problem as @phacic, here you can see the error and an application created from scratch with nativescript 4.2 and nativescript-imagecropper 1.0.4 and that gives the error.

Error link: https://ibb.co/dwVMD0
Application example link:  https://we.tl/t-9AjqpsNR1v

Please help.

**Comment by borjasanchez-bitcode** [comment]
> The issue is still present in tns 4.2 and nativescript-imagecropper 1.0.4
> 
> FAILURE: Build failed with an exception.
> What went wrong:
> Execution failed for task ':verifyReleaseResources'


I found a solution,
The problem is the gradle version, with version 4.6 it does not work, but with version 4.4 it works

**Comment by phacic** [comment]
From the android studio my gradle build is 4.4
