### ISSUE TITLE
The iOS Demo crashes with error: `Can't find variable: android`

### ISSUE THREAD

**Issue by frey1esm** [bthurlow/nativescript-imagecropper#34]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
**iOS**

- iOS/Android versions 
**11.3**

- emulator or device. What type of device?
**device - iPhone 7**

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
**4.1.1**

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
it's the ios demo

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
it's the ios demo

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
it's the ios demo

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 

I have not made any code edits. I just cloned the repo and tried to run the demo.

 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by shiv19** [comment]
@frey1esm Issue resolved :)
Thanks for letting us know
