### ISSUE TITLE
Nativescript-imagecropper throwing "image null" and "response error" in show() method

### ISSUE THREAD

**Issue by marojusantosh** [bthurlow/nativescript-imagecropper#39]
Hi
imageCropper.show method directly hits catch block and throws following error in the console:
JS: ==== object dump start ====
JS: response: “Error”
JS: image: “null”
JS: ==== object dump end ====

I have searched for the similar issue in the forum but it seems no one has posted yet.
I have taken the snippet from the npmjs document :

camera.takePicture({width:500,height:500,keepAspectRatio:true})
.then(function (imageAsset) {

                var source = new imageSource.ImageSource();
               var imageCropper = new ImageCropper.ImageCropper();
                source.fromAsset(imageAsset).then((imageSource1) => {
                    imageCropper.show(imageSource1,{lockSquare: true}).then((args) => {
                      if(args.image !== null){
                       imageView.imageSource = args.image;
                      }
                   })
                    .catch(function(e){
                     console.dir(e);
                    });
})
This issue occuring in both emulator and real mobiles with Android.

following are the dependencies and their versions I am using

**Package.json:**
“dependencies”: {
“nativescript-background-http”: “^3.3.0”,
“nativescript-bitmap-factory”: “^1.7.1”,
“nativescript-camera”: “^4.0.2”,
“nativescript-imagecropper”: “^1.0.4”,
“nativescript-imagepicker”: “^6.0.3”,
“nativescript-theme-core”: “~1.0.4”,
“tns-core-modules”: “^4.2.0”
}
please help.
Thanks in advance.

**Comment by marojusantosh** [comment]
com.yalantis.ucrop.UCrop is always undefined in imagecropper.android.js

**Comment by shiv19** [comment]
That means, you have to do
tns platform remove android

Then do
tns run android

**Comment by marojusantosh** [comment]
Great! That worked. Thank You:-)
