### ISSUE TITLE
Failed to build plugin nativescript-imagecropper ns 4.2 and 1.0.4 nativescript-imagecropper

### ISSUE THREAD

**Issue by borjasanchez-bitcode** [bthurlow/nativescript-imagecropper#41]
I have a problem that closed because I can not find the solution. I am using nativescript 4.2 and nativescript-imagecropper 1.0.4.

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':verifyReleaseResources'

Build failed with an exception.

![error](https://user-images.githubusercontent.com/37413118/47411332-a6371b00-d768-11e8-9bee-999a6a219ca0.png)

Please help.

**Comment by borjasanchez-bitcode** [comment]
The problem is the gradle version, with version 4.6 it does not work, but with version 4.4 it works

**Comment by samuelgonzalez1987** [comment]
OK borjasanchez, we will use 4.4 version. Thanks
