### ISSUE TITLE
IOS - Lock square image failed when undo icon clicked

### ISSUE THREAD

**Issue by LSmint** [bthurlow/nativescript-imagecropper#42]
Initially, the cropper size lock square aspect ratio on iOS, when try to click right rotate icon and then click undo icon, it no longer lock to square.

<img width="373" alt="screenshot 2018-10-29 at 11 13 51 pm" src="https://user-images.githubusercontent.com/35618399/47659626-51642c00-dbd0-11e8-9617-6b9d36271a46.png">

**Comment by LSmint** [comment]
Can include `viewController_1.resetAspectRatioEnabled = false;` if lockSquare is enabled.

**Comment by shiv19** [comment]
@LSmint
Can you make a PR for this please

**Comment by LSmint** [comment]
@shiv19 
Im sorry just noticed that this issue already fix in the release version. I will close the case.
