### ISSUE TITLE
How to use this plugin !

### ISSUE THREAD

**Issue by ahmed-derbala** [bthurlow/nativescript-imagecropper#45]
nativescript version 5.1

please I cant find how to use this plugin !

it just takes photos, I cant see any way to crop taken photos !!!!

**Comment by sanved77** [comment]
The demo code explains everything that is needed for this. Please read through the docs once.

**Comment by shiv19** [comment]
https://github.com/bthurlow/nativescript-imagecropper/issues/49#issuecomment-570948851
