### ISSUE TITLE
"No Page Available for Modal" Error on imageCropper.show()

### ISSUE THREAD

**Issue by kdagnan** [bthurlow/nativescript-imagecropper#54]
### Which platform(s) does your issue occur on?
- iOS 12 (Physical Device)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.3
- Cross-platform modules: 6.0.6
- Runtime(s): 6.0.1
- Plugin(s):  
![image](https://user-images.githubusercontent.com/44090970/63044744-dfc64780-be9c-11e9-824e-154820fdbe23.png)

I am calling the function after I receive an image from NS Camera+. 

`resizeImage(){
    var imageCropper = new this.ImageCropper();
    var width = 850;
    var height = 540;
    if(!this.horizontal){
        width = 540;
        height = 850;
    }
    imageCropper.show(this.originalImage,{width:width,height:height}).then((args) => {
    if(args.image !== null){
        this.imageSource = args.image;
    }
    })
    .catch(function(e){
        console.log(JSON.stringify(e));
        alert("Please make sure that your ID is the only thing visible in the image.");
        this.resizeImage();
    });
  }`

This was working at some point and I haven't touched the code but somewhere along the line it broke and I didn't realize it until recently as I have been working in other parts of my apps. The only things that would've changed are versions (TNS, Angular, iOS Platform, other plugins).

**Comment by shiv19** [comment]
Can you please pin your image cropper version to 1.0.5

1.0.6 doesn't work on iOS I'm going to unpublish it today

**Comment by kdagnan** [comment]
@shiv19 works on 1.0.5, thank you!
