### ISSUE TITLE
When i try to use this with image picker the code run fine on android 9 but and in android 10 the source is empty. 

### ISSUE THREAD

**Issue by RohanPhpDev** [bthurlow/nativescript-imagecropper#70]
I have tried this code in android 9 and its work but in android 10 I log the source and it shows null. 

const context = imagepickerModule.create({
    mode: 'single' // allow choosing single image
});
context
    .authorize()
    .then(function() {
        return context.present();
    })
    .then(function(selection) {
        selection.forEach(function(selected) {
            selected.getImageAsync(source => {
              if (source) {
                const selectedImgSource = imageSource.fromNativeSource(source);
                imageCropper
                    .show(selectedImgSource, { width: 500, height: 500 })
                    .then(args => {
                        if (args.image !== null) {
                          // Use args.image
                        }
                    })
                    .catch(function(e) {
                        console.log(e);
                    });
              }
            });
        });
    })
    .catch(function(e) {
        console.log(e);
    });
© 2020 GitHub, Inc.

**Comment by shiv19** [comment]
@RohanPhpDev 
please add this to your AndroidManifest.xml's application tag,
```xml
android:requestLegacyExternalStorage="true"
```

![image](https://user-images.githubusercontent.com/9407019/83483546-01112680-a4f7-11ea-954c-5b29a7b777f4.png)

**Comment by RohanPhpDev** [comment]
Thanx shiv19 now its works.
